spring:
  datasource:
    url: ENC(${URL_DB})
    username: ENC(${USERNAME_DB})
    password: ENC(${PDB})
    driver-class-name: ${DRIVE}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  application:
    name: ms-user-module
server:
  port: ${PORT}
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${JASYPT_ENCRYPTOR}
